# Generated by Django 4.0.6 on 2022-07-29 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_alter_post_post_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_content',
            field=models.CharField(default=1, max_length=400),
            preserve_default=False,
        ),
    ]
