# Generated by Django 4.0.4 on 2022-07-29 10:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0003_alter_post_post_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_like',
            field=models.ManyToManyField(related_name='post_like', to=settings.AUTH_USER_MODEL),
        ),
    ]
