# Generated by Django 3.2.6 on 2022-08-12 18:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_post_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='name',
        ),
        migrations.AddField(
            model_name='category',
            name='post_cate',
            field=models.CharField(default=1, max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='post_cate',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pst_ct', to='posts.category'),
        ),
    ]
