# Generated by Django 4.0.4 on 2022-07-29 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_alter_post_post_like'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='post_like',
        ),
    ]
