# Generated by Django 3.2.6 on 2022-08-15 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_alter_post_post_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_title',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
