# Generated by Django 4.0.6 on 2022-07-24 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=20)),
                ('user_pw', models.CharField(max_length=20)),
                ('user_quiz', models.CharField(max_length=50)),
            ],
        ),
    ]
